"""Add modified_by field to module table

Revision ID: 032f4ad10b14
Revises: 1d9280a23366
Create Date: 2025-01-15 15:05:58.985480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032f4ad10b14'
down_revision: Union[str, None] = '1d9280a23366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'module', 'user', ['modified_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'module', type_='foreignkey')
    op.drop_column('module', 'modified_by')
    # ### end Alembic commands ###
