"""Added is_super_admin to the user model for admin registration

Revision ID: 1d9280a23366
Revises: 2931cac31bd8
Create Date: 2025-01-10 19:32:38.764173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d9280a23366"
down_revision: Union[str, None] = "2931cac31bd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_super_admin", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_super_admin")
    # ### end Alembic commands ###
