"""Add temp_email column to User table

Revision ID: 2931cac31bd8
Revises: bab1ad0b432b
Create Date: 2025-01-08 20:23:36.103103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2931cac31bd8'
down_revision: Union[str, None] = 'bab1ad0b432b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('temp_email', sa.String(length=254), nullable=True))
    op.create_unique_constraint(None, 'user', ['temp_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'temp_email')
    # ### end Alembic commands ###
