"""Remove lives_remaining from progress table

Revision ID: 378a92cd87e2
Revises: 4342ae1ec395
Create Date: 2025-01-27 13:50:01.807788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378a92cd87e2'
down_revision: Union[str, None] = '4342ae1ec395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progress', 'lives_remaining')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('lives_remaining', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
