"""Add unique constraint to progress table

Revision ID: 4342ae1ec395
Revises: 7a0443cab042
Create Date: 2025-01-27 13:45:06.813239

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4342ae1ec395"
down_revision: Union[str, None] = "7a0443cab042"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_video")
    op.drop_index("ix_video_reference_video_id", table_name="video_reference")
    op.drop_table("video_reference")
    op.drop_constraint("user_lesson_unique", "progress", type_="unique")
    op.create_unique_constraint("uq_user_lesson", "progress", ["user_id", "lesson_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_lesson", "progress", type_="unique")
    op.create_unique_constraint(
        "user_lesson_unique", "progress", ["user_id", "lesson_id"]
    )
    op.create_table(
        "video_reference",
        sa.Column("video_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("gloss", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("signer_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "video_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("video_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("video_id", name="video_reference_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "ix_video_reference_video_id", "video_reference", ["video_id"], unique=False
    )
    op.create_table(
        "task_video",
        sa.Column("task_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("video_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.task_id"], name="fk_task_video_task", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.task_id"],
            name="fk_task_video_task_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video_reference.video_id"],
            name="fk_task_video_video",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video_reference.video_id"],
            name="fk_task_video_video_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("task_id", "video_id", name="task_video_pkey"),
    )
    # ### end Alembic commands ###
