"""Add is_verified column to User table

Revision ID: 9b6b32d532d0
Revises: 02ddd304864e
Create Date: 2024-12-18 18:12:20.296866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b6b32d532d0"
down_revision: Union[str, None] = "02ddd304864e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_verified", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_verified")
    # ### end Alembic commands ###
