"""Add avatar column to user model

Revision ID: bab1ad0b432b
Revises: 76399fcb0aef
Create Date: 2025-01-05 23:01:06.876227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bab1ad0b432b"
down_revision: Union[str, None] = "76399fcb0aef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "progress",
        "attempts",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("1"),
    )
    op.add_column("user", sa.Column("avatar", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "avatar")
    op.alter_column(
        "progress",
        "attempts",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("1"),
    )
    # ### end Alembic commands ###
